apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "myapp-operator.fullname" . }}-manager-role
  labels:
    {{- include "myapp-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["app.demo.io"]
    resources: ["myapps"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["app.demo.io"]
    resources: ["myapps/finalizers"]
    verbs: ["update"]
  - apiGroups: ["app.demo.io"]
    resources: ["myapps/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
